#ifndef MERCURY_RESOURCES_H
#define MERCURY_RESOURCES_H

#define MBAR_MENU 128

#define MENU_APPLE 128
#define MENU_CONNECTION 129
#define MENU_CHANNEL 130

#define MENU_APPLE_ABOUT 1
#define MENU_CONNECTION_QUIT 1

#define DLOG_CONN_INFO 128
#define DLOG_CONN_INFO_CONNECT 1
#define DLOG_CONN_INFO_QUIT 2
#define DLOG_CONN_INFO_HOST 6
#define DLOG_CONN_INFO_PORT 7
#define DLOG_CONN_INFO_NICK 8

#define ALRT_WARNING 128

#endif